server:
  port: 8089
spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.197.128
    port: 6379
    database: 0   #用第0个数据库